package part2;

/**
 * Generate markov model interface
 *
 */
public interface IMarkovModel {
    /**
     * Set training text with input string
     * @param text
     */
    public void setTraining(String text);

    /**
     * Set random with input seed
     * @param seed received from user input (args[1])
     */
    public void setSeed(int seed);

    /**
     * Generate random text relying on previous N (order of markov) chars
     *
     * next char is picked from a list generated by inner method - getFollows
     * @param numChars len of text to be generated
     * @return generated random text
     */
    public String getRandomText(int numChars);
    
}
